### PR TITLE
Fix search results links

### LINKED ISSUE #149: Typo results page
- Type in "No results" page saying jaas.io

### PR DESCRIPTION
**Pull request by carkod**
## Done

Fix links on search results page.

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8043/docs
- Type random words or strings in order to find No Results
- If you go to current site https://anbox-cloud.io/docs you will see jaas.io in the links, in this PR it will be corrected.

## Issue / Card

Fixes #149

### CODE REVIEW

**Comment by albertkol** [comment]
@carkod I need an anbox API key to QA it locally. 

Alternatively we can apply the fix we made for maas.io here: https://github.com/canonical-web-and-design/maas.io/commit/bd7d7c3302a21eedf4032bed81b61e0d3b288b10

That should fix the demo and allow me to QA there (maybe, not sure of demos have the API key).

**Comment by carkod** [comment]
> @carkod I need an anbox API key to QA it locally.
> 
> Alternatively we can apply the fix we made for maas.io here: [canonical-web-and-design/maas.io@bd7d7c3](https://github.com/canonical-web-and-design/maas.io/commit/bd7d7c3302a21eedf4032bed81b61e0d3b288b10)
> 
> That should fix the demo and allow me to QA there (maybe, not sure of demos have the API key).

Can you QA with the demo?

**Comment by carkod** [comment]
> @carkod I need an anbox API key to QA it locally.
> 
> Alternatively we can apply the fix we made for maas.io here: [canonical-web-and-design/maas.io@bd7d7c3](https://github.com/canonical-web-and-design/maas.io/commit/bd7d7c3302a21eedf4032bed81b61e0d3b288b10)
> 
> That should fix the demo and allow me to QA there (maybe, not sure of demos have the API key).

@albertkol  Sorry about that. Fixed.

**Review by albertkol — APPROVED** [review]
:+1:

**Pull request merged**
