### PR TITLE
Add k8s configuration in deploy/site.yaml

### PR DESCRIPTION
**Pull request by jkfran**
## Done

Add k8s configuration in deploy/site.yaml

https://github.com/canonical-web-and-design/snap-squad/issues/1367

### CODE REVIEW

**Comment by carkod** [comment]
How to QA this?

**Comment by jpmartinspt** [comment]
Install the konf snap and make sure this config applies in microk8s, it should since it's just a copy of the current production config.

**Comment by jpmartinspt** [comment]
I'm assigned to this though.

**Comment by carkod** [comment]
@jpmartinspt yep, I'll leave it to it. I just want to know how to QA in case one day I might do one

**Pull request merged**
