### PR TITLE
Bump cookie policy to v3.03

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- Bump cookie policy to v3.03
- Update GTM to track initial pageview

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8043/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- See that it is using cookie policy 3.03

### CODE REVIEW

**Comment by anthonydillon** [comment]
This one has a cornflake and is the script is not found on the homepage.

**Review by anthonydillon — CHANGES_REQUESTED** [review]
cookie-policy is 404ing.

**Comment by pmahnke** [comment]
have you tried it locally? seems fine

what's going on?

**Comment by pmahnke** [comment]
@anthonydillon updated the Dockerfile, should work now

**Review by anthonydillon — APPROVED** [review]
LGTM :+1:

**Review by anthonydillon — CHANGES_REQUESTED** [review]
You have two cookie policies in the package.json

**Comment by pmahnke** [comment]
@anthonydillon removed the dupe

**Review by anthonydillon — APPROVED** [review]
LGTM

**Pull request merged**
